### ISSUE TITLE
Add libre license

### ISSUE THREAD

**Issue by throwaway1037** [8051Enthusiast/8051Enthusiast.github.io#1]
Please may a [libre](https://freedomdefined.org) license be added to the project and the articles?

The articles are useful documentation. :)

I'd recommend CC-BY-SA-4.0-Int-or-later.

**Comment by throwaway1037** [comment]
Awesome! Thank you!

To clarify:
1. Does this apply to every file in the project?
2. Is it the -only or the -later version?
3. Does this apply retroactively to all past versions of the project? 

Also, it might be a good idea to add a license notice as a footer to every page so people know it's libre. :)

Once again, thank you very much! :)

**Comment by 8051Enthusiast** [comment]
I have added a footer to the website and a disclaimer in its about page which should clear this up some more.
1. This applies to every file in the project.
2. This is the -later version if I understood subsection 3(b) 1 right.
3. Yes.

**Comment by throwaway1037** [comment]
Thank you very much! :)
