### ISSUE TITLE
Reverse-engineering idea

### ISSUE THREAD

**Issue by throwaway1037** [8051Enthusiast/8051Enthusiast.github.io#2]
Dear @8051Enthusiast,

I have an idea for you which regards the `rtlwifi` firmware you wrote an article about.
How difficult do you think it would be to totally reverse-engineer the firmware and reimplement it as free (as in freedom) firmware?
The GNU Linux-libre project is a 100% libre fork of Linux kept synchronised with mainline Linux, except it has all the proprietary binary blobs removed.
I am sure they would love to add new libre firmware.
If you are interested, would you do this or help with the task?
You are evidently extremely knowledgeable and experienced with the 8051.
The blobs in question can be found at <https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/rtlwifi>.

Thank you.

**Comment by 8051Enthusiast** [comment]
Ah sorry, I must've missed the email for this issue and don't usually check issues for this repo.

Unfortunately, this would take a lot of time which I don't have.

In any case, it's possible to just not upload any firmware to the device at all, it will then fall back to the mask-rom firmware which does just the minimal work to keep it running (and most of the content is just machinery to allow firmware uploads).
